name = "harassment-platform-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Variables secretas (configurar con: wrangler secret put NOMBRE_VARIABLE)
# MONGODB_DATA_API_KEY = ""
# MONGODB_APP_ID = ""
# JWT_SECRET = ""
